CREATE DATABASE bibsysdb

CREATE TABLE usuarios (
	id SERIAL PRIMARY KEY,
	login VARCHAR(40) NOT NULL,
	senha TEXT NOT NULL
);

CREATE TABLE livros (
	id SERIAL PRIMARY KEY,
	nome TEXT NOT NULL,
	autor VARCHAR(100),
	editora VARCHAR(100),
	genero VARCHAR(100),
	estoque INTEGER DEFAULT 0
);

CREATE TABLE alunos {
	id SERIAL PRIMARY KEY,
	nome TEXT NOT NULL,
	periodo VARCHAR(40) NOT NULL,
	etapa VARCHAR(40) NOT NULL,
	ano INTEGER NOT NULL
}